-- DESIGNATION table
INSERT INTO DESIGNATION VALUES ('D001', 'Manager');
INSERT INTO DESIGNATION VALUES ('D002', 'Executive');
INSERT INTO DESIGNATION VALUES ('D003', 'Officer');
INSERT INTO DESIGNATION VALUES ('D004', 'Clerk');
INSERT INTO DESIGNATION VALUES ('D005', 'Helper');

-- DEPARTMENT table
INSERT INTO DEPARTMENT VALUES ('DP01', 'Personnel');
INSERT INTO DEPARTMENT VALUES ('DP02', 'Production');
INSERT INTO DEPARTMENT VALUES ('DP03', 'Purchase');
INSERT INTO DEPARTMENT VALUES ('DP04', 'Finance');
INSERT INTO DEPARTMENT VALUES ('DP05', 'Research');

-- EMPLOYEE table
INSERT INTO EMPLOYEE VALUES ('E001', 'Alice', 'DP01', 'D001', 'F', '45 Main St', 'Kolkata', 'WB', '700001', 50000, TO_DATE('2015-03-15', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE VALUES ('E002', 'Bob', 'DP02', 'D002', 'M', '22 Hill Rd', 'Delhi', 'DL', '110001', 40000, TO_DATE('2012-06-01', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE VALUES ('E003', 'Carol', 'DP03', 'D003', 'F', '19 River St', 'Mumbai', 'MH', '400001', 35000, TO_DATE('2018-01-10', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_CODE, EMP_NAME, DESIG_CODE, SEX, ADDRESS, CITY, STATE, PIN, JN_DT)
VALUES ('E004', 'David', 'D004', 'M', '7 South Ave', 'Chennai', 'TN', '600001', TO_DATE('2020-09-01', 'YYYY-MM-DD'));
SELECT * FROM EMPLOYEE WHERE DEPT_CODE IS NULL;
SELECT * FROM EMPLOYEE WHERE BASIC = 0;
SELECT * FROM EMPLOYEE WHERE BASIC IS NULL;
SELECT AVG(BASIC) AS AVG_BASIC FROM EMPLOYEE;
UPDATE EMPLOYEE SET BASIC = 0 WHERE BASIC IS NULL;
SELECT AVG(BASIC) AS AVG_BASIC_AFTER_UPDATE FROM EMPLOYEE;
DELETE FROM EMPLOYEE WHERE DEPT_CODE IS NULL;
SELECT EMP_NAME, BASIC + (BASIC * 0.5) + (BASIC * 0.4) AS NET_PAY FROM EMPLOYEE;
SELECT UPPER(EMP_NAME) AS EMP_NAME, BASIC FROM EMPLOYEE ORDER BY DEPT_CODE ASC;
SELECT * FROM EMPLOYEE WHERE JN_DT > TO_DATE('2010-01-01', 'YYYY-MM-DD');
SELECT COUNT(*) FROM EMPLOYEE WHERE EXTRACT(MONTH FROM JN_DT) = 1;
SELECT MAX(BASIC) AS MAX_BASIC, MIN(BASIC) AS MIN_BASIC FROM EMPLOYEE;
SELECT COUNT(*) AS FEMALE_COUNT FROM EMPLOYEE WHERE SEX = 'F';
UPDATE EMPLOYEE SET CITY = UPPER(CITY);
SELECT COUNT(DISTINCT CITY) AS UNIQUE_CITIES FROM EMPLOYEE;
SELECT * FROM EMPLOYEE ORDER BY DEPT_CODE ASC, BASIC DESC;