-- Assignment 2

-- Q1) Minimum, Maximum, and Average BASIC for each department
SELECT DEPT_CODE, 
       MIN(BASIC) AS Minimum, 
       MAX(BASIC) AS Maximum, 
       AVG(BASIC) AS Average 
FROM EMPLOYEE 
GROUP BY DEPT_CODE;

-- Q2) Number of female employees in each department
SELECT DEPT_CODE, COUNT(*) AS Female_Count 
FROM EMPLOYEE 
WHERE SEX = 'F' 
GROUP BY DEPT_CODE;

-- Q3) City-wise number of employees for each department
SELECT COUNT(*) AS No_Of_Employee, CITY, DEPT_CODE 
FROM EMPLOYEE  
GROUP BY CITY, DEPT_CODE;

-- Q4) Designation-wise number of employees who joined in 2000, ordered by count
SELECT COUNT(*) AS No_Of_Employee, DESIG_CODE 
FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM JN_DT) = 2000 
GROUP BY DESIG_CODE 
ORDER BY No_Of_Employee ASC;

-- Q5) Dept-wise total BASIC for male employees only, if total > 50000
SELECT DEPT_CODE, SUM(BASIC) AS Total_Basic 
FROM EMPLOYEE 
WHERE SEX = 'M' 
GROUP BY DEPT_CODE 
HAVING SUM(BASIC) > 50000 
ORDER BY Total_Basic DESC;

-- Q6) Employee name, Designation description and BASIC
SELECT EMP_NAME, DESIG_DESC, BASIC 
FROM EMPLOYEE 
JOIN DESIGNATION ON EMPLOYEE.DESIG_CODE = DESIGNATION.DESIG_CODE;

-- Q7) Employee name, Designation description, Department name & BASIC
SELECT EMP_NAME, DESIG_DESC, BASIC, DEPT_NAME 
FROM EMPLOYEE 
JOIN DESIGNATION ON EMPLOYEE.DESIG_CODE = DESIGNATION.DESIG_CODE 
JOIN DEPARTMENT ON EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_CODE;

-- Q8) Department codes with no employees
SELECT D.DEPT_CODE, COUNT(E.DEPT_CODE) 
FROM DEPARTMENT D 
LEFT OUTER JOIN EMPLOYEE E ON D.DEPT_CODE = E.DEPT_CODE 
GROUP BY D.DEPT_CODE 
HAVING COUNT(E.EMP_CODE) = 0;

-- Q9) Department names with at least one employee
SELECT D.DEPT_NAME 
FROM DEPARTMENT D 
LEFT OUTER JOIN EMPLOYEE E ON D.DEPT_CODE = E.DEPT_CODE 
GROUP BY D.DEPT_NAME 
HAVING COUNT(E.EMP_CODE) >= 1;

-- Q10) Departments where at least 10 employees work
SELECT D.DEPT_NAME 
FROM DEPARTMENT D 
LEFT OUTER JOIN EMPLOYEE E ON D.DEPT_CODE = E.DEPT_CODE 
GROUP BY D.DEPT_NAME 
HAVING COUNT(E.EMP_CODE) >= 10;

-- Q11) Dept code of employee with highest BASIC
SELECT DEPT_CODE 
FROM EMPLOYEE 
WHERE BASIC = (SELECT MAX(BASIC) FROM EMPLOYEE);

-- Q12) Designation description of employee with highest BASIC
SELECT DESIG_DESC 
FROM DESIGNATION 
WHERE DESIG_CODE = (
  SELECT DESIG_CODE FROM EMPLOYEE 
  WHERE BASIC = (SELECT MAX(BASIC) FROM EMPLOYEE)
);

-- Q13) Number of managers in each department
SELECT E.DEPT_CODE, COUNT(*) AS Manager_Count 
FROM EMPLOYEE E 
JOIN DESIGNATION D ON E.DESIG_CODE = D.DESIG_CODE 
WHERE UPPER(D.DESIG_DESC) = 'MANAGER' 
GROUP BY E.DEPT_CODE;

-- Q14) Maximum BASIC without using MAX()
SELECT BASIC 
FROM (
  SELECT BASIC 
  FROM EMPLOYEE 
  ORDER BY BASIC DESC
) 
WHERE ROWNUM = 1;

-- Q15) Minimum BASIC without using MIN()
SELECT BASIC 
FROM EMPLOYEE 
ORDER BY BASIC ASC 
FETCH FIRST 1 ROWS ONLY;

-- Q16) Dept with:
-- a) Highest total basic
SELECT DEP.DEPT_NAME 
FROM EMPLOYEE E 
JOIN DEPARTMENT DEP ON E.DEPT_CODE = DEP.DEPT_CODE 
GROUP BY DEP.DEPT_NAME 
ORDER BY SUM(E.BASIC) DESC 
FETCH FIRST 1 ROWS ONLY;

-- b) Highest average basic
SELECT DEP.DEPT_NAME 
FROM EMPLOYEE E 
JOIN DEPARTMENT DEP ON E.DEPT_CODE = DEP.DEPT_CODE 
GROUP BY DEP.DEPT_NAME 
ORDER BY AVG(E.BASIC) DESC 
FETCH FIRST 1 ROWS ONLY;

-- c) Maximum number of employees
SELECT DEP.DEPT_NAME 
FROM EMPLOYEE E 
JOIN DEPARTMENT DEP ON E.DEPT_CODE = DEP.DEPT_CODE 
GROUP BY DEP.DEPT_NAME 
ORDER BY COUNT(E.EMP_CODE) DESC 
FETCH FIRST 1 ROWS ONLY;

-- Q17) Insert invalid DESIGNATION rows into EMPLOYEE
INSERT INTO EMPLOYEE VALUES (
  'EMP011', 'JAIDIP SARKAR', 'DP04', 'DESIG008', 'M',
  'Nowhere, Bullygaunje', 'KOLKATA', 'WEST BENGAL', '325801', 116000, TO_DATE('19-02-2003','DD-MM-YYYY')
);
INSERT INTO EMPLOYEE VALUES (
  'EMP012', 'JOYDIPTO BISWAS', 'DP01', 'DESIG010', 'F',
  'Anywhere, Garia', 'KOLKATA', 'WEST BENGAL', '700112', 80000, TO_DATE('17-10-1999','DD-MM-YYYY')
);

-- Q18) Delete rows with invalid DESIGNATION
DELETE FROM EMPLOYEE 
WHERE DESIG_CODE NOT IN (SELECT DESIG_CODE FROM DESIGNATION);

-- Q19) Female employees whose BASIC > avg of their department
SELECT E.EMP_NAME 
FROM EMPLOYEE E 
WHERE SEX = 'F' 
AND BASIC > (
  SELECT AVG(BASIC) 
  FROM EMPLOYEE 
  WHERE DEPT_CODE = E.DEPT_CODE
);

-- Q20) Number of female managers
SELECT COUNT(*) AS female_managers 
FROM EMPLOYEE E 
JOIN DESIGNATION D ON E.DESIG_CODE = D.DESIG_CODE 
WHERE SEX = 'F' AND UPPER(D.DESIG_DESC) = 'MANAGER';
